"""escalation reason and per-bot turn threshold

Revision ID: c37e229a7075
Revises: af6c196a6fdf
Create Date: 2026-09-06 00:12:55.967230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c37e229a7075'
down_revision: Union[str, Sequence[str], None] = 'af6c196a6fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('escalation_max_bot_turns', sa.Integer(), server_default='3', nullable=False))
    op.add_column('conversations', sa.Column('escalation_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'escalation_reason')
    op.drop_column('bots', 'escalation_max_bot_turns')
    # ### end Alembic commands ###
