"""inbound events and failed jobs

Revision ID: f2de7ad16da0
Revises: 243f3fa1ee04
Create Date: 2026-09-05 19:10:02.823557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2de7ad16da0'
down_revision: Union[str, Sequence[str], None] = '243f3fa1ee04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_events',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_update_id', sa.String(length=191), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['channel_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_update_id', name='uq_inbound_events_dedupe')
    )
    op.create_index(op.f('ix_inbound_events_connection_id'), 'inbound_events', ['connection_id'], unique=False)
    op.create_index(op.f('ix_inbound_events_status'), 'inbound_events', ['status'], unique=False)
    op.create_table('failed_jobs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('connection_id', sa.BigInteger(), nullable=True),
    sa.Column('inbound_event_id', sa.BigInteger(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['channel_connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inbound_event_id'], ['inbound_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_jobs_connection_id'), 'failed_jobs', ['connection_id'], unique=False)
    op.create_index(op.f('ix_failed_jobs_kind'), 'failed_jobs', ['kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_failed_jobs_kind'), table_name='failed_jobs')
    op.drop_index(op.f('ix_failed_jobs_connection_id'), table_name='failed_jobs')
    op.drop_table('failed_jobs')
    op.drop_index(op.f('ix_inbound_events_status'), table_name='inbound_events')
    op.drop_index(op.f('ix_inbound_events_connection_id'), table_name='inbound_events')
    op.drop_table('inbound_events')
    # ### end Alembic commands ###
